// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnmkivgbuwudagjnusiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxubWtpdmdidXd1ZGFnam51c2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1MTU0NzAsImV4cCI6MjA2NjA5MTQ3MH0.ghMlzwwxfhbcQY-k_QBHeODiWxNoFN7BAQjPIcitkME";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);